### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FObermaier** [craftworkgames/FarseerPhysics.Portable#3]
Which license applies to this library?

**Comment by craftworkgames** [comment]
Hi @FObermaier 

This is a fork of the Farseer Physics Engine found on codeplex with a few minor changes to make it work as a Portable Class Library (PCL) with the PCL version of MonoGame. It is provided under the same Microsoft Permissive License (Ms-PL) v1.1 (Ms-PL) as the original source code.

You can find the original source code here: http://farseerphysics.codeplex.com/

I've updated the readme with this info.
