### ISSUE TITLE
Please include XML documentation with nuget package.

### ISSUE THREAD

**Issue by Petoj87** [craftworkgames/FarseerPhysics.Portable#5]
Please include the xml documentation so we get some information in the IntelliSense.

**Comment by craftworkgames** [comment]
Good idea.

I must admit I haven't given this project much attention lately. Do you know off the top of your head how to generate the docs? I assume it's just some sort of project setting?

If you are interested in doing some legwork I'd be happy to accept a pull request.

**Comment by Petoj87** [comment]
They should be generated by default I guess you just need to include them in your nuget file.

**Comment by Inverness** [comment]
The IDE doesn't select XML documentation by default for some reason.

In any case, I've made a pull request with the change: https://github.com/craftworkgames/FarseerPhysics.Portable/pull/6

**Comment by craftworkgames** [comment]
Great work. Thanks :smile:

**Comment by craftworkgames** [comment]
It's been a while since I've rebuilt the NuGet package. I'll add it to my TODO list to get this done for you.
